# 阶段 1：编译层
FROM ubuntu:24.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive

# 复制本地源码
COPY RSFSRC /root/RSFSRC
WORKDIR /root/RSFSRC

# 安装依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc gfortran make cmake scons \
    libx11-dev libxt-dev libxext-dev libxaw7-dev \
    libpng-dev libjpeg-dev libtiff-dev \
    python3 python-is-python3

# 编译安装
RUN ./configure --prefix=/root/RSFAPP \
    && make -j$(nproc) \
    && make install


# 阶段 2：运行层
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# 安装运行库
RUN apt-get update && apt-get install -y --no-install-recommends \
    libx11-6 libxt6 libxext6 libxaw7 \
    libpng16-16 libjpeg-turbo8 libtiff6 \
    python3 python-is-python3 scons \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /root/RSFDATA /root/RSFRUN

# 从编译层复制
COPY --from=builder /root/RSFAPP /root/RSFAPP

# 环境变量
ENV RSFROOT=/root/RSFAPP/
ENV RSFDATA=/root/RSFDATA/
ENV DATAPATH=/root/RSFDATA/
ENV PATH=$RSFROOT/bin:$PATH
ENV MANPATH=$RSFROOT/share/man:/usr/share/man
ENV LD_LIBRARY_PATH=$RSFROOT/lib:$LD_LIBRARY_PATH
ENV PYTHONPATH=$RSFROOT/lib/python3.12/site-packages:$PYTHONPATH
ENV JULIA_LOAD_PATH=$RSFROOT/lib:${JULIA_LOAD_PATH}:

WORKDIR /root/RSFRUN
CMD ["bash"]
